obj-m   += bruteforce.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

# KDIR    := /lib/modules/$(shell uname -r)/build
# PWD    := $(shell pwd)
#default:
#    $(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
